---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

resources:
  - 00-telco-gitops-ns.yaml
  - 01-cli-job-sa-and-role.yaml
  - 02-hook-postsync-csv.yaml
  - 05-telco-gitops-ztp.yaml
  - 10-core-telco-base.yaml
  - 10-core-telco-apps.yaml
